### ISSUE TITLE
Column access to tables

### ISSUE THREAD

**Issue by hyanwong** [hyanwong/GeneticInheritanceGraph#19]
With #17 we have defined a simple table structure, but we have no simple way to get a numpy array of the columns, for instance, we might hope to be able to get

```python
child_left = TableCollection.intervals.child_left
```

Or even set a whole column:

```python
TableCollection.intervals.child_left = child_left +1
```

(we can't even do the latter in tskit, though)

**Comment by duncanMR** [comment]
I'd be happy to take this one on. I will see if I can replicate how its done with tskit data.

**Comment by hyanwong** [comment]
Great. We could probably do a bit better than `tskit` for the interface. For example, it would be good to have something like this:

https://github.com/tskit-dev/tskit/issues/2015

It would be much better if we could use `tables.nodes.time[x]` to get direct memory access, rather than the somewhat clunky `ts.nodes_time[x]`. You might well want to talk to @benjeffery about this. 

Do make sure, however, that we aren' "prematurely optimising". For the size of datasets we are experimenting on, there's no need to make this fast (yet). It's better to get a slow API that can be sped up later, under the hood.

Once we get to this stage, it's vital to start setting up unit tests, so #20 is important to tackle at the same time.
