### ISSUE TITLE
Create testing infrastructure

### ISSUE THREAD

**Issue by hyanwong** [hyanwong/GeneticInheritanceGraph#20]
Now that we have some draft code, we could probably do with setting up a simple testing infrastructure framework, using pytest. It would be nice if this was run automatically for any PR, but that doesn't have to be the case, I guess.

Presumably copying something like the tskit testing framework would be sensible? Thoughts @duncanMR? Have you dealt with much unit testing before?

**Comment by duncanMR** [comment]
We'll definitely need to do this at some point. I've written a few tests, but I've never set up a testing system before. I'd like to learn how, though, so I'd like to take this one on. I think it would be sensible to start by writing the tests with pytest, then later figure out how to automatically run them with any PR?

**Comment by hyanwong** [comment]
The infrastructure is basically there now, although the tests aren't. I will leave this open until we've made a few PRs to test that it's all working.

**Comment by hyanwong** [comment]
An easy task is to get coverage up to 100% in tables.py and util.py. See 

https://app.codecov.io/gh/hyanwong/GeneticInheritanceGraph/tree/main/GeneticInheritanceGraph

**Comment by duncanMR** [comment]
Great, I'll get some tests up and running today!

**Comment by hyanwong** [comment]
The two example tests in test_tables.py should show you (a) how to use fixtures (e.g. if you want to import a standard GIG for testing in multiple tests) and (b) how to use `@pytest.mark.parametrize` to test a range of parameter values. Both of these are useful idioms.

**Comment by hyanwong** [comment]
Seems to work OK now. Closing.
