### ISSUE TITLE
Make method to convert a GIG table into a Pandas dataframe

### ISSUE THREAD

**Issue by duncanMR** [hyanwong/GeneticInheritanceGraph#34]
While we have a GIG data model, we still lack basic methods to do things like subsetting (e.g. `intervals[intervals.parent == 2]`) and sorting by a particular column. If we convert a GIG table to a Pandas DataFrame, doing such basic data manipulation is trivial, so I think having such a conversion method available will be useful for exploratory work. It will be hard to do subsetting and sorting more efficiently than Pandas without resorting to the tricks used in tskit, so I'm inclined to kick that down the road for now.

**Comment by hyanwong** [comment]
Yes, we could reasonably use pandas for the moment, as long as we don't end up relying on pandas functions in the scripts we write.

**Comment by hyanwong** [comment]
A conversion to a pandas dataframe is quite reasonable anyway. FWIW in tsdate, to avoid a pandas dependency we just have an `asdict` method (or something like that), so you can do `df = pd.DataFrame(obj.asdict())`, but maybe that's too long a thing to type here, and we just want an `obj.df()` method?

**Comment by duncanMR** [comment]
> A conversion to a pandas dataframe is quite reasonable anyway. FWIW in tsdate, to avoid a pandas dependency we just have an `asdict` method (or something like that), so you can do `df = pd.DataFrame(obj.asdict())`, but maybe that's too long a thing to type here, and we just want an `obj.df()` method?

I'm inclined to go for the latter for now, since I don't have any use for the dict object outside of turning it into a dataframe. I'm only going to use Pandas in exploratory work, so it won't be any trouble to drop the Pandas dependency later, I think?
