### ISSUE TITLE
Switch to integer coordinate space

### ISSUE THREAD

**Issue by hyanwong** [hyanwong/GeneticInheritanceGraph#39]
It seems like it could be a good idea to switch to a discrete genome rather than a continuous one like in tskit. The main motivation for this is to fix the problem of combining half-closed intervals with inversions. If we had discrete coordinates then we could have all intervals as inclusive, so that e.g. [0, 1], [2, 4], [5-9] would be contiguous intervals covering a genome of length 10.

This would mean we could have an interval of [0, 0] (covering 1 base pair), but I think that's OK. What do you think @duncanMR ?

**Comment by duncanMR** [comment]
I think we can solve the half-closed intervals with inversions issue with some carefully chosen conventions, but I do agree that integer coordinates makes a lot of sense (especially biologically). What was the rationale for choosing to make the genome continuous in tskit/msprime?

**Comment by hyanwong** [comment]
Switched in #43
