### ISSUE TITLE
Rename "Interval" or "Edge" to "IEdge"

### ISSUE THREAD

**Issue by hyanwong** [hyanwong/GeneticInheritanceGraph#42]
There was some debate about whether to call the "edges" in a GIG "intervals" or "edges". As Jerome pointed out, and we have in the ARG paper, the representation in tskit is essentially an "interval-edge" (or "edge-interval"), which stores, in a denormalised form, both the edge information (parent & child) coupled with the edge information.

I think to avoid confusion, we should simply call this the "iedge" (pronounced eye-edge, like iPhone) table. I also think we should have an extra row which states the edge index, in case we want multiple edges over the same interval which have the same parent & child. This turns out to be necessary for full representation of diamonds in an ARG, and I think we might want it in a GIG. By default we can leave this as `-1` for the time being. When we turn a set of tables into a GIG, we can populate any `-1` values with the same positive ID if they share a parent/child combination.

**Comment by duncanMR** [comment]
I agree on both counts; having an edge index will definitely come in handy. Shall we rename IntervalTableRow to IEdgeTableRow then?

**Comment by hyanwong** [comment]
I think so. I'm about to do that and will make a PR
