### ISSUE TITLE
When to check GIG consistency

### ISSUE THREAD

**Issue by hyanwong** [hyanwong/GeneticInheritanceGraph#45]
In general, I think it's a good idea to allow the GIG Tables to contain data which is inconsistent with a GIG (e.g. NaN times, parents younger than children, etc), but we check on the GIG requirements when converting to a Graph object.

One exception to this is the numerical type of the input values. E.g. if we assign a (noninteger) floating point number to a `child_left` coordinate in a Table, do we raise an error? Or do we only raise the error when converting to a graph. I suspect that in the future we will want to store the table data in numpy arrays of a given type, so we should probably do this check when creating the table data, rather than when converting to a graph.

At the moment, we don't do this. The following doesn't raise an error, and I think it probably should

```python
Tables.iedges.add_row(0, 1, 0.1, 5, 1.1, 6)
```

**Comment by duncanMR** [comment]
We absolutely should check types when adding rows to the table; I don't see any reason not to. In addition, I suggest that we require that `parent_left < parent_right` at that stage, since any inversion-related code will likely break otherwise. I agree that we should leave all the other checks for graph conversion.

**Comment by hyanwong** [comment]
> We absolutely should check types when adding rows to the table; I don't see any reason not to. 

Great, I agree.

> In addition, I suggest that we require that `parent_left < parent_right` at that stage, since any inversion-related code will likely break otherwise. I agree that we should leave all the other checks for graph conversion.

I think there are a whole set of checks that won't make sense unless consistency is checked (e.g. what if abs(child_left-chiuld_right) != abs(parent_left-parent_right). I think we should leave all these checks to be performed when creating a GIG from the tables, rather than when making the tables themselves.

What makes me think this is that there have been times in tskit when I deliberately wanted to make inconsistent tables, then correct them before turning them into a tree sequence

**Comment by hyanwong** [comment]
Superseded by #48
